version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Limelemon1@
      POSTGRES_DB: research_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./BackEnd
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:Limelemon1%40@db:5432/research_db
    depends_on:
      - db

  frontend:
    build: ./FrontEnd/frontend/frontend
    restart: always
    volumes:
      - frontend_build:/app/build
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
  frontend_build: